jotaen/klog

- docs/Specification.md
I believe the the specification intends that if the minute part is missing (not the hours) from a duration, the minutes part is assumed to be zero minutes.
> Typo (hour -> minute)

- src/app/cli/cmd_append.go
- src/app/cli/common_args.go
- src/app/cli/exec.go
- src/app/cli/testutil_test.go
- src/app/context.go
- src/app/mac_widget/render_darwin.go
- src/app/mac_widget/run_darwin.go
- src/service/evaluate.go
- src/service/evaluate_test.go
- src/service/lookup.go
- src/service/lookup_test.go
- src/service/template.go
- src/service/template_test.go
In the long run it would be great if the CLI was also capable of manipulating files. As explained in #3 this is not trivial to build, so a first step would already be to append new data to an existing file.
This PR introduces an experimental `append` subcommand. It will be included in the `v1.1` release, albeit still hidden. (So you can use the feature if you know the command, but neither does it show up in the main help nor is it documented).
The idea is this: You can have template files in `~/.klog/` suffixed with `.template.klg`. For example, `~/.klog/work.template.klg`, which could contain this:
```
{{TODAY}} (8h!)
Yet another day at work...
{{NOW}} - ?
```
The template files are basically regular klog files, but they can contain placeholders: currently `{{TODAY}}`, `{{YESTERDAY}}` …
> Add experimental support for templates and appending

- src/app/cli/cmd_json.go
- src/app/cli/cmd_now.go
- src/app/cli/cmd_report.go
- src/app/cli/cmd_total.go
- src/app/cli/exec.go
- src/app/mac_widget/render_darwin.go
- src/parser/json/serialiser.go
- src/parser/json/serialiser_test.go
- src/parser/json/view.go
- src/parser/parser_test.go
- src/service/evaluate.go
- src/summary.go
- src/summary_test.go
In order to allow people to build tooling around klog in a convenient way, the topic of a JSON API has come up in various contexts. This PR addresses https://github.com/jotaen/klog/issues/15 and introduces a JSON command that turns klog input file(s) into a structures JSON output.
The command is still configured to be hidden from the help text, since the JSON structure might not be final yet. The command will be `klog json` or `klog json myfile.klg` respectively.
> Provide “JSON” API for programmatic extensions

- CHANGELOG.md
- src/app/cli/cmd_json.go
- src/parser/error.go
- src/parser/json/serialiser.go
- src/parser/json/serialiser_test.go
- src/parser/json/view.go
- src/parser/parsing/error.go
- src/parser/parsing/error_test.go
On https://github.com/jotaen/klog/issues/15
- `column` in the error output now takes indentation into account
- You can filter and sort the same way as with other commands `klog json --before 2020-12-31 --tag work`
- Put an empty array `"tags":[]` if there are no tags, instead of `"tags":null`
- Split error message into title and details
> Smaller fixes and tweaks for the JSON command

- CHANGELOG.md
- src/app/cli/cmd_bookmark.go
- src/app/cli/cmd_json.go
- src/app/cli/testutil_test.go
- src/app/context.go
- src/app/fileutil.go
- src/parser/json/serialiser.go
- src/parser/json/serialiser_test.go
Mixed bag of things:
- Add `--pretty` flag for `klog json`, to make output more discoverable by humans
- Read from stdin, to allow piping input, e.g. `cat myfile.klg | klog total`. That also ties into making programatic access easier via 3rd party tools
- Add `bookmark unset` to clear the current bookmark
> Prettify JSON, support stdin, `bookmark unset`

- CHANGELOG.md
- src/app/cli/common_args.go
- src/app/cli/exec.go
- src/app/cli/lib/period.go
- src/app/cli/lib/period_test.go
- src/date_test.go
- src/service/query.go
- src/service/query_test.go
- Make `--before` and `--after` exclusive
- Introduce `--until` and `--since` as inclusive equivalents
- Introduce `--period` for calendric date ranges such as `--period=2018` or `--period=2018-09`
- Group all filters in the help text output
- Don’t display help text output anymore when given malformed flags
Fixes https://github.com/jotaen/klog/issues/31.
> Change and extend CLI filters

- Specification.md
- src/app/cli/create.go
- src/app/cli/lib/common_args.go
- src/parser/error.go
- src/service/evaluate.go
Fixes https://github.com/jotaen/klog/issues/62. @vladdeSV would you mind looking at the spec changes and double-check whether it makes sense? 🙏🏼
Changes:
- Remove concept of “properties” from the spec
- Use consistent spelling in the CLI (with a dash: `should-total`)
- Rephrase error messages
The notion of properties still appears internally in the parser code, since it helps to distinguish error cases. The term is not user-facing anymore, though.
> Abandon abstract concept of “properties”

- src/app/cli/start.go
- src/app/cli/start_test.go
- src/app/cli/stop.go
- src/app/cli/stop_test.go
- src/parser/reconciler.go
- src/parser/reconciler_test.go
Fixes https://github.com/jotaen/klog/issues/36.
> Add flags for setting the summary when calling `start`/`stop`

- src/app/context.go
- src/app/ioutil.go
Addresses https://github.com/jotaen/klog/issues/66, where the removal of the previous bookmark failed but klog just swallowed the error. The error handling now explicitly checks for the expected error and fails in case something else goes wrong.
> Make clearing the bookmark more robust

- src/app/cli/create.go
- src/app/cli/lib/reconciler_helper.go
- src/app/cli/start.go
- src/app/cli/start_test.go
- src/app/cli/stop.go
- src/app/cli/stop_test.go
- src/app/cli/track.go
- src/app/cli/track_test.go
- src/parser/reconciler.go
Fixes https://github.com/jotaen/klog/issues/60 and https://github.com/jotaen/klog/issues/59:
- If `start` and `track` don’t find an applicable record, they just create it on the fly. (Before it failed.)
- When doing `stop` it now also considers the previous day and closes that range with a shifted time
> Auto create on `start` or `track`; also consider “yesterday” for `stop`

- src/service/query.go
- src/service/query_test.go
- src/summary.go
- src/summary_test.go
Fixes https://github.com/jotaen/klog/issues/56, so you can do `--tag=foo...` now when filtering on the CLI.
I eventually went with the `...` operator instead of `*`, because the latter is usually caught by shells and interpreted as glob pattern, so you would be forced to quote (`--tag='foo*'`) which is inconvenient. I also assume that wildcards are only useful at the end of the string to support hierarchical tag structures (e.g. `#category_something` → `--tag=category_...`).
> Support wilcard tag filtering via `...` operator

- src/app/cli/create.go
- src/app/cli/lib/common_args.go
- src/app/cli/lib/format.go
- src/app/cli/lib/format_test.go
- src/app/cli/lib/reconciler_helper.go
- src/app/cli/lib/textutil.go
- src/app/cli/main/klog.go
- src/app/cli/now.go
- src/app/cli/print.go
- src/app/cli/report.go
- src/app/cli/start.go
- src/app/cli/stop.go
- src/app/cli/tags.go
- src/app/cli/testutil_test.go
- src/app/cli/total.go
- src/app/cli/track.go
- src/app/context.go
- src/app/mac_widget/run_darwin.go
- src/parser/integration_test.go
- src/parser/serialiser.go
- src/parser/serialiser_test.go
Fixes https://github.com/jotaen/klog/issues/78
Fixes https://github.com/jotaen/klog/issues/79
- Inject serialiser via the context. That’s cleaner and more robust than accessing a singleton instance.
- Add `SignedDuration` on serialiser to avoid having additional logic in the override objects
- Add tests for error rendering to avoid future regressions
- Fix trailing spaces in line-breaking utility
> Fix CLI formatting issues

- CHANGELOG.md
- src/app/cli/index.go
- src/app/cli/now.go
- src/app/cli/now_test.go
- src/app/cli/report.go
- src/app/cli/report_test.go
- src/app/cli/today.go
- src/app/cli/today_test.go
Additionally fix for https://github.com/jotaen/klog/issues/27.
- Make `--now` optional. Due to the new structure the command can also useful be without the `--now` option. Plus, it’s more inline with the other commands, e.g. `klog total --now` or `klog report --now`.
- Rename `klog now` to `klog today`. The idea of this command is to give an overview of the total times, with separate evaluations for today and all other records.
- When there are no current records, display `n/a` in that row. Before, the command would just print an error message, which is not very user-friendly.
- Add more tests
> Refactor `klog today` command (formerly `klog now`)

- src/duration.go
- src/duration_test.go
Fixes https://github.com/jotaen/klog/issues/86 according to spec.
```
2021-07-07
2h59m     Okay
60m       Okay (fixed)
120m      Okay (fixed)
2h60m     Not okay
1h1237m   Not okay
```
> Allow minute part in durations to be >60 when there is no hour part

- src/app/cli/index.go
- src/app/cli/info.go
- src/app/cli/main/klog.go
Fixes https://github.com/jotaen/klog/issues/99.
It’s tricky with the CLI library I’m using, because it doesn’t support flags that are scoped to the base command, it rather passes on all “global“ flags to subcommands. Therefore, it’s not possible to support `klog -v`, since that wouldn’t allow `klog foo -v` anymore.
On the bright side, I added a default command, so if you run `klog` as is (without subcommand), it will print a friendly info message instead of an error.
> Support `--version` in addition to the subcommand

- src/app/context.go
- src/app/ioutil_unix.go
- src/app/ioutil_windows.go
Fixes https://github.com/jotaen/klog/issues/94.
This is more a small convenience feature, so the goal is not to maintain a comprehensive list of all possible editors out there.
> Guess editors if `$EDITOR` is not set

- Specification.md
@vladdeSV next try to fix https://github.com/jotaen/klog/issues/90.
[See here for Unicode space separator category.](https://www.compart.com/en/unicode/category/Zs)
> Clarify definition of whitespace (blank characters)

- Specification.md
I’d like to make a minor, but important modification to the spec, which is also a breaking change. In order to move forward with https://github.com/jotaen/klog/issues/51, it’s important to enforce a consistent indentation style within records. Otherwise, the following problem could occur with multiline entry summaries, when using 2 spaces as indentation style:
```
2020-01-01
4h With the upcoming multiline entry summaries,
text can continue on the next line with increased indentation level.
```
The 2 space indentation style is ambiguous, because 2*2=4, and 4 spaces is also allowed as indentation. If the indentation style was required to be consistent, the ambiguity would be resolved.
> Require indentation style to be consistent within records

- go.mod
- go.sum
- src/app/commands/print_test.go
- src/app/lib/common_args.go
Due to a bug in the underlying CLI library I use, the default for the `--sort` flag couldn’t be empty. [That was fixed now](https://github.com/alecthomas/kong/issues/250), so the behaviour now is that without `--sort` flag, the records are printed out in the order they appear in the file.
> Default to unsorted if no `--sort` flag specific

- src/app/commands/create.go
- src/app/commands/start.go
- src/app/commands/stop.go
- src/app/commands/testutil_test.go
- src/app/commands/today.go
- src/app/commands/track.go
- src/app/commands/widget/render.go
- src/app/context.go
- src/app/lib/args.go
- src/app/lib/commons.go
- src/date.go
- src/parser/reconciling/reconciler.go
- src/parser/reconciling/reconciler_test.go
- src/service/datetime.go
- src/service/datetime_test.go
- src/service/evaluate.go
- src/service/sanitycheck.go
- src/service/sanitycheck_test.go
- src/time.go
- src/time_test.go
When evaluating files, klog shows warnings if it detects potential logical problems in the file. These warnings are now also shown when using the manipulation commands.
The warnings also have been slightly improved:
- It detects overlaps for open time ranges now, e.g.:
```
2021-01-01
8:00-10:00
9:00-?
```
It also issues a warning if there is a time range that starts *after* the open range start time, because that’s most likely a mistake:
```
2021-01-01
15:00-16:00
9:00-?
```
- For detecting future entries, it doesn’t just look at the date, but also at the time. E.g., say right now it was `15:00` at the 1.1.2021, then the following would cause a warning:
```
2021-01-01
12:00 - 16:00
19:00> - ?
```
What is okay, though, is this: (“tomorrow’s” date, but the times are shifted back)
``` …
```
> Also issue warnings when manipulating files

- Specification.md
“Non-functional” refactoring of the specification for improved clarity.
- Add examples for all concepts (except summaries) and structure every section in the same way:
- Brief explanation of what it is on a high-level
- Examples (formatted as markdown blockquote)
- Detailed instructions
- Remove redundant statement “Each record must contain a date”, since that’s already clear from the record specification.
- Remove statement for entry summaries “there may be multiple spaces”. This is superfluous, because everything after the first space is treated as part of the summary copy, and an entry summary is allowed to contain (and hence start with) any character.
- Remove term “immediately” (e.g. `MUST be immediately followed by the character`) – that sounds a bit dramatic and doesn’t add any …
> Spec: Restructuring and more examples

- src/parser/engine/indentation_test.go
- src/parser/integration_test.go
- src/parser/parser.go
- src/parser/parser_test.go
- src/parser/reconciling/reconciler.go
- src/parser/reconciling/reconciler_test.go
- src/summary.go
- src/summary_test.go
Fixes https://github.com/jotaen/klog/issues/51 by allowing to continue an entry summary on the next line (on the next indentation level).
```
2020-01-01
5h30m A multiline entry summary
can contain multiple lines of
text, which are indented twice.
8:00 - 9:00
Or, you can also directly start on
the subsequent line.
9:00 - 10:00 If you like, you can also
add more whitespace, for visual
alignment. (I.e. the indentation
is *at least* twice.)
````
~It’s still WIP, since I want to do some more testing. Also, the spec needs to be updated.~ Spec changes will follow in separate PR.
> Parse and process multiline entry summaries

- .github/workflows/release.yml
- Due to the removed macOS widget, there is no native (Objective-C) code anymore that needs separate compiling. For simplicity of the process, the build for all target platforms can now run on Linux.
- Truncate the embedded changelog to the latest 5 releases, to avoid continuously increasing the binary size over time
> Update build scripts for release

- src/parser/reconciling/append_entry.go
- src/parser/reconciling/append_entry_test.go
- src/parser/reconciling/close_open_range.go
- src/parser/reconciling/close_open_range_test.go
- src/parser/reconciling/pause_open_range.go
- src/parser/reconciling/reconciler.go
- src/parser/reconciling/start_open_range.go
- src/parser/reconciling/start_open_range_test.go
You can now include line breaks (`\n`) when providing an entry summary from the CLI, and it will automatically convert that to a multiline entry summary with correct indentation.
E.g. `klog start --summary 'This note has\nmultiple lines.'`:
```
2000-01-01
14:00-? This note has
multiple lines.
```
Or `klog track`, e.g. `klog track '8:30 - 10:00\nIntense workout in the gym'`:
```
2000-01-01
8:30 - 10:00
Intense workout in the gym
```
> Improve multiline summary support on the CLI

- .github/workflows/ci.yml
Bring back staticcheck, once it’s compatible with Go 1.18. (Should be included in the [next release](https://github.com/dominikh/go-tools/releases).)
(Originally disabled via https://github.com/jotaen/klog/pull/164.)
> Re-enable staticcheck

- src/app/cli/lib/args.go
- src/app/cli/main/cli_test.go
- src/app/cli/main/decoder.go
- src/service/period/period.go
- src/service/period/period_test.go
- src/service/period/quarter.go
- src/service/period/quarter_test.go
- src/service/period/week.go
- src/service/period/week_test.go
Resolves https://github.com/jotaen/klog/issues/178.
Add two new patterns for period filtering:
- `YYYY-Qq`, e.g. `2022-Q1` for all records in the first quarter of 2022
- `YYYY-Www`, e.g. `2022-W04`/`2022-W4` for all records in the fourth week of 2022 (week number as of ISO 8601)
> Allow `--period` filtering by week and quarter

- src/app/cli/lib/args.go
- src/app/cli/main/cli.go
- src/app/cli/main/cli_test.go
- src/app/cli/main/decoder.go
- src/app/cli/print.go
- src/app/cli/tags.go
- src/app/cli/tags_test.go
- src/service/evaluate.go
- src/service/query.go
- src/service/query_test.go
- src/service/tags.go
- src/service/tags_test.go
- src/summary.go
- src/summary_test.go
- src/tag.go
- src/tag_test.go
Resolves the CLI implementation of https://github.com/jotaen/klog/issues/169, the spec part is yet to be written.
Tags can now (optionally) have values assigned to them, e.g. `#tag=value`, `#ticket=163` or `#team="Super Heros"`.
If you consider this file:
```
2020-04-14
1h30m Entry 1 #ticket=4
2h15m Entry 2 #ticket=1
2020-04-16
#ticket
6h Entry 3
```
Then filtering for…
- `--tag ticket` will match entries 1, 2, 3
- `--tag ticket=4` will only match entry 1
- `--tag ticket=8` won’t match anything
When listing all tags via `klog tags --values`, it outputs:
```
#ticket 9h45m      
1            2h15m
4            1h30m
```
> Support assigning values to tags

- README.md
- Specification.md
Release the spec into the public domain, under the dual license [CC0 1.0](http://creativecommons.org/publicdomain/zero/1.0/) & [OWFa 1.0](https://www.openwebfoundation.org/the-agreements/the-owf-1-0-agreements-granted-claims/owfa-1-0).
Resolves https://github.com/jotaen/klog/issues/173.
Thank you again @vladdeSV for all your contributions to the spec (and of course for maintaining the VSCode extension)! 🚀
> Release specification into the public domain (CC0/OWFa)

- Specification.md
Along with https://github.com/jotaen/klog/pull/180, resolves https://github.com/jotaen/klog/issues/169.
This change is backwards compatible, i.e. tags *without* values work the same as before.
> Allow tags to have values

- Specification.md
Resolves https://github.com/jotaen/klog/issues/163 (see https://github.com/jotaen/klog/discussions/162 originally).
@vladdeSV what do you think? Would that cover the question sufficiently?
I’m not 100% sure whether this should only be recommended (`SHOULD`) or mandatory (`MUST`). If it was mandatory, it could be interpreted that e.g. a syntax highlighter would have to stop working completely if there is an invalid token in the file, but that wouldn’t be very helpful. A recommendation would avoid that, as it leaves some room for “common sense”, while still having a clear opinion basically.
> Specify how to deal with invalid input

- Specification.md
There are a lot of rules in the spec whose underlying reasoning is implicit, for example [why the `?` placeholder in open ranges can be repeated](https://github.com/jotaen/klog/discussions/92).
It would be good to preserve that knowledge somehow, because it makes it easier to understand how the rules came to be.
I’d think the right place to do that would be in “information” footnotes. That way, the spec keeps reading cleanly, but the context information is still embedded into it.
This PR is WIP for now, in order to experiment with this idea.
Footnotes are also not available in all markdown dialects, so I need to decide how to format it. As an aside, it could be useful to mention a markdown standard that the spec is written in, e.g. CommonMark (and which version).
[See here for a rendered …
> Add footnotes for preserving contextual background info

- src/app/cli/lib/args.go
- src/service/query.go
- src/service/query_test.go
This is a small fix that’s needed so that filtering follows a consistent system, which is that the filter flags are combined via a logical `AND`. E.g.
```
klog total --since 2020-04-01 --until 2020-04-30 --tag foo --tag bar`
```
would match all records in April 2020, that contain both tags `#foo` and `#bar`.
A specific date is necessarily exclusive, though, so it doesn’t make sense that multiple ones can be specified.
> Only support single `--date` filter

- src/app/cli/bookmarks.go
- src/app/cli/main/cli_test.go
Tiny fix: when setting a bookmark, the output now differentiates between whether the bookmark was new or overriden.
```
$ klog bookmark set ~/foo.klg foo
Created new bookmark:
@foo -> ~/foo.klg
$ klog bookmark set ~/bar.klg foo
Changed bookmark:
@foo -> ~/bar.klg
```
> Fix output when setting bookmark

- src/app/cli/lib/args.go
- src/app/cli/report.go
- src/app/cli/tags.go
- src/app/cli/today.go
- src/app/cli/total.go
- src/app/cli/total_test.go
- src/service/evaluate.go
- src/service/evaluate_test.go
- src/service/record.go
- src/service/record_test.go
Fixes https://github.com/jotaen/klog/issues/196.
The `--now` flag is now available for `klog tags` as well.
Also, the error handling is improved now: previously, it would just ignore uncloseable time ranges, i.e. when the record’s date was before yesterday, so that the open range cannot be closed with a shifted time anymore. Now, all commands that consume `--now` will raise an error in that case.
> Support `--now` on `klog tags` and improve error handling

- src/app/cli/create.go
- src/app/cli/create_test.go
- src/app/cli/main/cli.go
- src/app/cli/main/cli_test.go
- src/app/cli/main/decoder.go
- src/app/cli/start.go
- src/app/cli/track.go
- src/parser/reconciling/creator.go
- src/parser/reconciling/creator_test.go
Fixes https://github.com/jotaen/klog/issues/195.
Examples:
- `klog create --summary 'Test record' file.klg`
- `klog create --summary 'Test record\nwith multiple\nsummary lines' file.klg`
> Support setting a summary when creating a record (via `klog create --summary`)

- src/app/context.go
- src/app/sys_darwin.go
- src/app/sys_linux.go
- src/app/sys_windows.go
I wrote a simple parse function to split arguments. The parser allows multiple spaces between arguments and can parse quoted arguments. The function also removed the quotes from the first argument as it is expected to be the executable.
I also made it so `tryCommands` logs all errors from failed commands.
Tell me if there anything I can fix or improve in this pull request. Otherwise, the pull request is ready to be merged (if the changes are wanted).
Fixes #206
> Fix command argument splitting to parse quoted arguments

- klog/app/cli/lib/helper.go
- klog/app/cli/print.go
- klog/app/cli/print_test.go
- klog/app/cli/report.go
- klog/parser/integration_test.go
- klog/parser/serialiser.go
- klog/parser/serialiser_test.go
Resolves https://github.com/jotaen/klog/issues/189.
```
klog print --with-totals myfile.klg
```
Contrary to the draft output in the issue, a two-column output makes more sense, to separate the subtotals from the entries and the overall totals (i.e. the sum of the subtotals) from the records.
In theory, this could also support `--diff`, `--now`, `--decimal`, etc., but I feel that’s a bit too much for the `klog print` command.
> Optionally amend `klog print` output with total values

- klog/app/cli/report.go
- klog/app/cli/report_test.go
Resolves https://github.com/jotaen/klog/issues/221.
That was an odd edge-case in the `klog report` command, where it failed with an index-out-of-bounds panic, in case you use the `--fill`/`-f` option **and** when the filtered data set is empty. (See [`report.go:45-47`](https://github.com/jotaen/klog/blob/039da4da3ceb9be67dcdd63819810b2f6160339d/klog/app/cli/report.go#L45-L47).)
> Fix panic edge-case in report command

- .github/benchmark.go
- .github/benchmark.sh
- .github/workflows/ci.yml
- klog/parser/integration_test.go
- klog/parser/serialiser.go
- klog/parser/serialiser_test.go
This PR adds a benchmark that’s automatically executed during the build on the CI. The benchmark creates a temporary `.klg` file, which is seeded with 10.000 randomly generated records. It then measures the time it takes for `klog total` to evaluate all that data.
On the Github Action runners (which have slightly-below-average computing power, compared to up-to-date commodity hardware), the benchmark runtime seems to be somewhere in the range of 600ms–800ms.
For comparison, 1 year worth of data (i.e., 365 records) would take ~30ms to evaluate, which I think is sufficiently fast.
Should I ever get around to it, the implementation of `klog` would probably allow for some relatively straightforward performance wins, e.g. by parallelising the record parsing, or by making smarter assumptions …
> Set up benchmark on CI

- .github/benchmark.sh
- klog/app/cli/main/cli.go
- klog/app/cli/testutil_test.go
- klog/app/context.go
- klog/parser/engine.go
- klog/parser/engine/block.go
- klog/parser/engine/block_test.go
- klog/parser/engine/line.go
- klog/parser/engine/line_test.go
- klog/parser/engine/parallel.go
- klog/parser/engine/serial.go
- klog/parser/engine2/parallel.go
- klog/parser/engine2/serial.go
- klog/parser/integration_test.go
- klog/parser/parser.go
- klog/parser/parser_test.go
- klog/parser/reconciling/append_entry_test.go
- klog/parser/reconciling/close_open_range_test.go
- klog/parser/reconciling/creator_test.go
- klog/parser/reconciling/pause_open_range_test.go
- klog/parser/reconciling/reconciler.go
- klog/parser/reconciling/start_open_range_test.go
- klog/parser/style_test.go
- klog/summary.go
This PR cuts the parsing time roughly in half:
- All regexes are cached now (~20% speed-up)
- The memory allocations are optimised, so it avoids dynamic allocations where possible (~5% speed-up)
- Records are parsed in parallel, so it utilises all cores of the machine (~20% speed-up)
- The preprocessing algorithm is simplified, and doesn’t rely on regexes anymore (~5% speed-up)
The improvements are only noticeable on larger data-sets, i.e. > 500 records. For smaller ones, it’s the same as before.
|Number of records|Before|After|
|-|-|-|
|10|15ms|15ms|
|100|20ms|20ms|
|1.000|60ms|35ms|
|10.000|480ms|210ms|
|100.000|4.500ms|2.000ms|
(The numbers depend on machine and test data-set, but the overall trend should be representative.)
> Optimise parsing performance

- .github/benchmark.sh
Run multiple batch sizes, in 3 iterations each:
```
1:  0.008s  0.008s  0.008s  
10:  0.009s  0.008s  0.008s  
100:  0.010s  0.011s  0.010s  
1000:  0.039s  0.037s  0.040s  
10000:  0.275s  0.279s  0.274s
```
(Before, it was just one iteration with a batch size of 10.000.)
> Make benchmark more differentiated

- klog/app/cli/lib/cli_serialiser.go
- klog/app/cli/tags.go
- klog/app/cli/tags_test.go
- klog/parser/serialiser.go
- klog/service/tags.go
- klog/service/tags_test.go
Resolves https://github.com/jotaen/klog/issues/227.
Note, `--count` does not count how often a tag *appears* in the file, but how many entries *match* against it. I.e., the tag count for the following data is 4:
```
2000-01-01
#foo All 3 entries below match:
1h
2h
3h
2000-01-02
1h #foo #foo This entry is only counted once
```
It also works in conjunction with `--values`.
> Optionally display count in `klog tags`

- go.mod
- go.sum
- klog.go
- klog/app/cli/edit.go
- klog/app/cli/edit_test.go
- klog/app/cli/goto_test.go
- klog/app/cli/lib/command/command.go
Resolves https://github.com/jotaen/klog/issues/230.
- `$EDITOR` can now contain flags, such as `subl --wait` or `vi -R`
- In case the binary path itself contains spaces, it must be quoted, so that klog is able to distinguish the full path from any additional flags. E.g.
`EDITOR='"C:\Program Files\Sublime Text" --wait'`
- Instead of `$EDITOR`, you can alternatively specify `$KLOG_EDITOR`. This is for the case where quoting would create problems for other programs that can’t handle quotes in `$EDITOR`. That way, you can configure a klog-specific override, which takes precedence over `$EDITOR`.
> Support `$EDITOR` containing flags

- klog/app/cli/lib/cli_serialiser.go
- klog/app/cli/lib/helper.go
- klog/app/cli/pause.go
- klog/app/cli/testcontext_test.go
- klog/app/context.go
- klog/parser/reconciling/close_open_range.go
- klog/parser/reconciling/pause_open_range.go
- klog/parser/reconciling/pause_open_range_test.go
- klog/parser/reconciling/reconciler.go
Resolves https://github.com/jotaen/klog/issues/228.
This PR simplifies the logic of `klog pause`:
- `klog pause` appends a new pause entry to the record
- The pause entry will be added as last entry
- It adds the new entry directly, without waiting out the first minute. During the first minute, the entry value is `-0m`.
- There is no auto-magic auto-extending of existing pause entries
- If `--extend` is specified, it keeps adding to the last pause entry
- If `--summary` is specified, the summary text will be appended to the existing pause entry
- If there is no pause entry, the command fails
> Simplify logic of `klog pause`

- klog/app/cli/json.go
- klog/app/cli/lib/args.go
- klog/app/cli/lib/helper.go
- klog/app/cli/lib/prettifier.go
- klog/app/cli/print.go
- klog/app/cli/report.go
- klog/app/cli/tags.go
- klog/app/cli/today.go
- klog/app/cli/today_test.go
- klog/app/cli/total.go
- klog/service/record.go
- klog/service/record_test.go
Resolves https://github.com/jotaen/klog/issues/245.
When specifying `--now` without any open-ended time range being present in the data, then klog emits a warning, so that users are aware that the flag didn’t take any effect. For `klog today`, the forecasted end-time is additionally put into parentheses and rendered in subdued colour, to indicate that you are currently not actively moving towards the time goal.
I also thought about the topic from the ticket what to do once the end-time has been reached, and whether it should be hidden in this case. I eventually think one can make good points either way: on the one hand, it’s true that the end-time is mostly interesting while it’s in the future. On the other hand, it might also potentially be interesting to know like “I could have gone …
> Improve UI around `--now` flag

- go.mod
- klog.go
- klog/app/cli/config.go
- klog/app/cli/create.go
- klog/app/cli/create_test.go
- klog/app/cli/index.go
- klog/app/cli/info.go
- klog/app/cli/lib/args.go
- klog/app/cli/lib/prettifier.go
- klog/app/cli/main/cli.go
- klog/app/cli/main/testutil_test.go
- klog/app/cli/start.go
- klog/app/cli/start_test.go
- klog/app/cli/stop.go
- klog/app/cli/stop_test.go
- klog/app/cli/testcontext_test.go
- klog/app/cli/track.go
- klog/app/cli/track_test.go
- klog/app/config.go
- klog/app/config_test.go
- klog/app/context.go
- klog/app/file.go
- klog/service/rounding.go
- klog/service/rounding_test.go
This PR addresses https://github.com/jotaen/klog/discussions/158.
klog now looks for a config file at `~/.klog/config.yml`, where users are able to specify some preferences. For now, that is:
- `default_rounding`: the value for the `--round` flag, unless specified, e.g. in `klog start` or `klog stop`.
- `default_should_total`: the default for the `--should-total` flag, unless specified, that is used whenever klog creates a new record, e.g. in `klog create`, but also in `klog track` or `klog start`, as these might create new records on the fly.
More configuration parameters may follow later, now that the groundwork is set up.
When the config file is absent, everything behaves as before, so it’s strictly optional right now.
What’s also new is that klog will respect the …
> Introduce file-based user configuration

- klog.go
- klog/app/cli/config.go
- klog/app/cli/index.go
- klog/app/cli/info.go
- klog/app/cli/main/cli.go
- klog/app/cli/testcontext_test.go
- klog/app/context.go
- klog/app/error.go
- klog/app/file.go
- klog/app/sys.go
- klog/app/sys_darwin.go
- klog/app/sys_linux.go
- klog/app/sys_windows.go
Resolves https://github.com/jotaen/klog/issues/250.
The lookup order for klog’s config folder (previously referred to as “klog folder”, residing at `~/.klog` by default on all OS’es) is now this:
- macOS:
- `$KLOG_CONFIG_HOME` (expects full path including the “suffix” bit, so you can also set it to be `/foo/bar/all-my-klog-configs` if that fancies you)
- `$XDG_CONFIG_HOME/klog` (for XDG-addicts that stranded on macOS for some reason)
- `$HOME/.klog` (the default / most “idiomatic” config location on macOS)
- Linux:
- `$KLOG_CONFIG_HOME` (see above)
- `$XDG_CONFIG_HOME/klog`
- `$HOME/.config/klog` (the default / most “idiomatic” config location on Linux)
- Windows
- `%KLOG_CONFIG_HOME%` (see above)
- `%AppData%\klog` (the default / most “idiomatic” config location on Windows)
klog iterates …
> Change location of klog config folder

- INSTALL.md
provide a cleaner way to make the downloaded but not properly signed binary executable
> update macOS install instructions

- CHANGELOG.md
- klog/app/cli/create.go
- klog/app/cli/index.go
- klog/app/cli/lib/helper.go
- klog/app/cli/pause.go
- klog/app/cli/start.go
- klog/app/cli/stop.go
- klog/app/cli/switch.go
- klog/app/cli/switch_test.go
- klog/app/cli/testcontext_test.go
- klog/app/cli/track.go
- klog/app/context.go
- klog/parser/reconciling/append_entry.go
- klog/parser/reconciling/append_entry_test.go
- klog/parser/reconciling/close_open_range.go
- klog/parser/reconciling/close_open_range_test.go
- klog/parser/reconciling/creator_test.go
- klog/parser/reconciling/pause_open_range.go
- klog/parser/reconciling/pause_open_range_test.go
- klog/parser/reconciling/reconciler.go
- klog/parser/reconciling/start_open_range.go
- klog/parser/reconciling/start_open_range_test.go
Resolves https://github.com/jotaen/klog/issues/268.
`klog switch` stops an ongoing activity (open range) and starts a new one at the same time. It’s basically a convenience shortcut for separately issuing `klog stop` and `klog start` – with a few subtle differences, though:
- The command is atomic, so it only writes to the file once. The end time of the previously open range and the start time of the newly opened range are guaranteed to be the same.
- The command doesn’t have fallback-behaviour. It neither falls back to the previous date like `klog stop` does, nor would it create a new record like `klog start` would.
- A summary for the new entry can be specified via the `-s`/`--summary` flag. Appending to the summary for the previously open range is not possible.
The command deliberately …
> Add command `klog switch`

- CHANGELOG.md
- klog/app/cli/start.go
- klog/app/cli/start_test.go
Resolves https://github.com/jotaen/klog/issues/266.
In case there is no record at the current date, `klog start --resume` now falls back to the previous record for determining the last entry summary. E.g., for this file:
```
2020-01-01
14:00-15:00 Something
```
Say today was `2020-01-02` + `13:39`, then `klog start --resume` would yield:
```
2020-01-01
14:00-15:00 Something
2020-01-02
13:39-? Something
```
Previously, the newly created entry wouldn’t have had a summary.
> Make `klog start --resume` fall back to previous record

- CHANGELOG.md
- klog/app/cli/lib/args.go
- klog/app/config_test.go
- klog/service/rounding.go
- klog/service/rounding_test.go
Add two new rounding options: `12m` and `20m`. That way, all whole fractions of 60 are supported (from 1–12, with the exception of 10/`6m`).
> Add rounding options `12m` and `20m`

- klog/app/cli/print_test.go
- klog/parser/serialiser.go
There was a bug when printing records with multiline summaries with the `--with-totals` flag.
It used to print:
```
8h15m  |  2018-03-26
|  Line 1
Line 2
2h45m  |      8:30 - 11:15 asdf
|          asdf
|          asdf
|          asdf
1h5m  |      11:15 - 12:20
4h25m  |      13:30 - 17:55`
```
Where it should (and now does) print:
```
8h15m  |  2018-03-26
|  Line 1
|  Line 2
2h45m  |      8:30 - 11:15 asdf
|          asdf
|          asdf
|          asdf
1h5m  |      11:15 - 12:20
4h25m  |      13:30 - 17:55
```
> Fix `print --with-totals` for multiline record summaries

- klog/app/cli/terminalformat/colour_theme.go
- klog/app/config.go
Resolves https://github.com/jotaen/klog/issues/289.
klog now supports light-themed terminals via the `colour_scheme = light` entry in the `config.ini` file (see `klog config --help`).
> Introduce light colour theme

- klog/app/cli/util/prettifier.go
- klog/app/cli/util/prettifier_test.go
- klog/app/context.go
- klog/app/main/cli_test.go
- klog/parser/txt/error.go
Resolves https://github.com/jotaen/klog/issues/278.
> Preserve file name for syntax errors

- klog/app/cli/create.go
- klog/app/cli/report.go
- klog/app/cli/util/args.go
- klog/app/main/cli.go
- klog/app/main/cli_test.go
- klog/app/main/decoder.go
- klog/service/query.go
- klog/service/query_test.go
Resolves https://github.com/jotaen/klog/issues/286.
This let’s you do `klog total --entry-type duration` (for only summing up duration entries) or `klog print --entry-type open-range` (for only showing open ranges).
> Add option to filter by entry type

- klog/app/cli/pause.go
- klog/parser/reconciling/pause_open_range.go
- klog/parser/reconciling/pause_open_range_test.go
- klog/summary.go
- klog/summary_test.go
Resolves https://github.com/jotaen/klog/issues/283.
If the open range contains tags, then `klog pause` will automatically take them over (i.e., append) them to the pause entry.
```
2000-01-01
5:00-? Did #work
```
Then `klog pause` yields:
```
2000-01-01
5:00-? Did #work
-0m #work
```
You can still use the `--summary` flag.
`--no-tags` disables this behaviour.
> Auto-appending tags from open range when pausing

- klog/app/cli/index.go
- klog/app/cli/start.go
- klog/app/cli/start_test.go
Resolves https://github.com/jotaen/klog/issues/282.
You can now specify which entry to resume – e.g.:
- `--resume-nth=1` takes over the summary of the first entry
- `--resume-nth=2` takes over the summary of the second entry
- `--resume-nth=-1` takes over the summary of the last entry
- `--resume-nth=-2` takes over the summary of the second-to-last entry
You can also use the shorthand `-N`. Remember to omit the delimiter after the flag name then, so it would be `-N1`, `-N2`, `-N-1`, `-N-2`, etc.
> Support `--resume-nth`/`-N` flag for `klog start`

- klog/app/cli/bookmarks.go
- klog/app/file.go
- klog/app/main/cli_test.go
Resolves https://github.com/jotaen/klog/issues/310
> Add `--create` flag for `klog bookmarks set`

- klog/app/cli/util/args.go
- klog/app/config.go
- klog/app/config_test.go
- klog/service/warning.go
- klog/service/warning_test.go
My use case ends up with a lot of overlapping entries as I tag a certain timeperiod multiple times and instead of passing --no-warn each time I would like to just throw this into a configurable and be done with it.
> Config option to disable warnings

- klog/app/cli/start.go
- klog/app/cli/start_test.go
- klog/app/cli/switch.go
- klog/app/cli/switch_test.go
- klog/app/cli/util/args.go
Resolves https://github.com/jotaen/klog/issues/327, by making available the `--resume`/`--resume-nth` flags on the `klog switch` subcommand.
> Add “resume” flags to `klog switch`

- go.mod
- go.sum
- klog/app/error.go
- klog/app/main/cli.go
- klog/app/main/cli_test.go
- klog/app/main/testutil_test.go
Upgrade Go dependencies.
kong changed their internal error processing in their `1.3.0` release (by introducing `errors.Wrap`), which requires a code adjustment.
> Upgrade dependencies

- klog/date_test.go
- klog/duration.go
- klog/duration_test.go
- klog/time_test.go
This PR adds a few tests to make sure that we don’t accidentally accept any kinds of digits that aren’t Arabic numerals.
> Ensure to not parse “exotic” digits

- CHANGELOG.md
- klog/app/cli/report.go
- klog/app/cli/report_test.go
Related https://github.com/jotaen/klog/discussions/336.
This PR adds a `--chart` (`-c`) flag to the `klog report` command, which includes bar chart diagrams in the output like so:
```
$ klog report --chart worktimes.klg
Total                                  
2025 Jan    Tue 14.       6h  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇        
Thu 16.    7h30m  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇  
Fri 17.    6h45m  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇     
Sat 18.       8h  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
Mon 20.    3h20m  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇                  
Wed 22.    7h45m  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 
Sat 25.    7h15m  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇   
========                                  
46h35m                                  
```
The default resolution of the bars depends on the aggregation mode. (Remember: …
> Provide `--chart` flag on `klog report` command

- klog/app/cli/tags.go
- klog/app/cli/tags_test.go
- klog/app/cli/terminalformat/table.go
- klog/app/cli/terminalformat/table_test.go
- klog/service/tags.go
- klog/service/tags_test.go
See https://github.com/jotaen/klog/discussions/342.
This PR introduces a new flag `--with-untagged` / `-u` for the `klog tags` subcommand, which includes any untagged entries in the overview.
E.g., for a file `example.klg` like this …
```
2000-01-01
1h #something
2h
```
… running `klog tags --with-untagged example.klg` would yield:
```
#something 1h
(untagged) 2h
```
The `(untagged)` special row always appears last.
> Optionally include untagged entries in `klog tags`

- klog/app/cli/bookmarks.go
- klog/app/cli/config.go
- klog/app/cli/index.go
- klog/app/cli/info.go
The semantics around `klog config` and `klog info config-folder` are a bit confusing. This PR consolidates all config-related documentation into the `klog config` command. `klog info config-folder` has now become `klog config --location`.
> Consolidate documentation on config folder
