docs/Specification.md
Minor corrections and phrasing improvements.
Turned draft into RFC and added note about that.
=> Fileformat v1 rfc

Specification.md
As discussed, closes https://github.com/jotaen/klog/issues/9
@vladdeSV could you have a final look please?
=> Clarifications about ranges and blank lines between records

.github/workflows/release.yml, CHANGELOG.md, README.md, src/app/context.go, src/app/ioutil_unix.go, src/app/ioutil_windows.go
Fixes https://github.com/jotaen/klog/issues/19, thanks @vladdeSV
=> Provide native binary for Windows

Specification.md
Fixes https://github.com/jotaen/klog/issues/63 by clarifying explanations and adding some (already existing but unmentioned) concepts explicitly.
I’d consider the Specification largely done for v1 with this PR, so I’m probably going to revoke the RFC/Draft status afterwards.
- Improve and clarify existing descriptions
- Explain concept of “open range” separately
- Explicitly mention the concept of time “shifting”
- Explain how total times are supposed to be computed
- Allow Windows line endings
=> Specification: improve explanations and add some missing concepts

Specification.md, src/app/cli/version.go
The specification seems to be good to go, so the first stable version can be released soon.
This PR can be used to discuss all final bits and pieces, be it the overall structure or nitty-gritty details. I’ll leave it open for a week or so.
cc @vladdeSV
=> Release v1.0 of the specification

src/app/cli/report.go, src/app/cli/report/aggregator.go, src/app/cli/report/day.go, src/app/cli/report/month.go, src/app/cli/report/quarter.go, src/app/cli/report/week.go, src/app/cli/report/year.go, src/app/cli/report_test.go, src/date.go, src/date_test.go, src/service/datehash.go, src/service/datehash_test.go, src/service/query.go
Fixes https://github.com/jotaen/klog/issues/93, so you can now aggregate by different categories.
=> Add different aggregation options for `klog report`

.github/workflows/release.yml, INSTALL.md
See https://github.com/jotaen/klog/issues/114.
=> Generate binaries for Mac M1 (ARM)

src/app/commands/report_test.go, src/parser/error.go, src/parser/parser.go, src/parser/parser_test.go, src/parser/reconciling/reconciler_test.go, src/record.go
According to the upcoming spec changes https://github.com/jotaen/klog/pull/122.
=> Require indentation within records to be uniform

Specification.md
All upcoming changes to the Spec are collected on this branch (`spec/next`).
=> Next release of the Specification (Version 1.1)

src/app/commands/print_test.go, src/parser/parser_test.go, src/time.go, src/time_test.go
Fixes https://github.com/jotaen/klog/issues/130.
=> Accept `24:00` as valid time

src/app/commands/report/week.go, src/app/commands/report_test.go, src/date.go, src/date_test.go, src/service/period/period_test.go, src/service/period/week.go
Fixes https://github.com/jotaen/klog/issues/143.
=> Fix week-based aggregation

Specification.md, src/record.go
- https://github.com/jotaen/klog/pull/133
- https://github.com/jotaen/klog/pull/134
=> Spec: Version 1.2

src/app/lib/args.go, src/app/main/cli.go, src/service/period/month.go, src/service/period/month_test.go, src/service/period/period.go, src/service/period/quarter.go, src/service/period/quarter_test.go, src/service/period/week.go, src/service/period/week_test.go, src/service/period/year.go, src/service/period/year_test.go
Fixes https://github.com/jotaen/klog/issues/140.
=> Add more shortcut filters (`--this-week`, `--last-month`, etc.)

src/app/cli/index.go, src/app/cli/lib/commons.go, src/app/cli/lib/with_repeat.go, src/app/cli/main/cli.go, src/app/cli/pause.go, src/app/cli/testutil_test.go, src/app/cli/today.go, src/app/context.go, src/parser/reconciling/pause_open_range.go, src/parser/reconciling/pause_open_range_test.go, src/record_test.go, src/summary.go, src/summary_test.go
Resolves https://github.com/jotaen/klog/issues/155.
=> Add pause function for open time ranges

src/summary.go, src/summary_test.go
Resolves https://github.com/jotaen/klog/issues/168.
Spec is adjusted via https://github.com/jotaen/klog/pull/170.
=> Allow hyphens to appear in tags

README.md, Specification.md, src/record.go
PR for collecting upcoming spec changes. The planned changes are:
- https://github.com/jotaen/klog/issues/173
- https://github.com/jotaen/klog/issues/168
- https://github.com/jotaen/klog/issues/169
- https://github.com/jotaen/klog/issues/163
- https://github.com/jotaen/klog/pull/167
=> Next version of spec

CHANGELOG.md
- https://github.com/jotaen/klog/issues/168
- https://github.com/jotaen/klog/pull/179
- https://github.com/jotaen/klog/issues/173
- https://github.com/jotaen/klog/issues/169
- https://github.com/jotaen/klog/issues/163
=> Changelog for next version

klog/app/cli/json.go
Resolves https://github.com/jotaen/klog/issues/229.
=> Provide `--now` flag in `klog json`

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md
Set up templates for creating new issues.
=> Set up issue templates

CHANGELOG.md, README.md
=> Upcoming changes

klog/app/cli/config.go, klog/app/cli/lib/args.go, klog/app/cli/today.go
- Add `--no-style` option for `klog config` (to allow stdout>file redirection)
- Improve help texts
=> Minor fixes for release

klog/app/cli/start.go, klog/app/cli/start_test.go
Resolves https://github.com/jotaen/klog/issues/258.
The `--resume` / `-R` flag takes over the last entry summary when starting a new entry. If there is no previous entry, or if the previous entry summary is empty, it doesn’t create a summary for the new entry. The `--resume` flag cannot be used together with the `--summary` flag.
Note, the `-r` shorthand flag was already reserved by `--round`.
=> Add `--resume` flag for `klog start`

CHANGELOG.md, README.md
Add release dates to changelog, just for the protocol.
=> Preserve release date in changelog

CHANGELOG.md
- https://github.com/jotaen/klog/issues/282
- https://github.com/jotaen/klog/pull/311
=> Changelog for next release

klog/app/cli/tags_test.go, klog/app/cli/terminalformat/table.go, klog/app/cli/terminalformat/table_test.go
Resolves https://github.com/jotaen/klog/issues/322.
=> Fix output alignment with Unicode characters
